### ISSUE TITLE
Develop JS for pattern behavior

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#106]
@kristianserrano commented on [Tue Dec 04 2018](https://github.com/emory-libraries/web-redesign/issues/58)

---

@nikdragovic commented on [Tue Jan 08 2019](https://github.com/emory-libraries/web-redesign/issues/58#issuecomment-452314229)

Revisit this issue - needs to be broken down by patterns (reference spreadsheet)

**Comment by laurenhamel** [comment]
I'm wondering if this issue is still relevant? It seems like a holdover from startup as we were trying to figure out how issues should be broken down and what our workflows would look like. Since we agreed that the JS development gets incorporated into the pattern library work, could we close this issue?

**Comment by nikdragovic** [comment]
I agree and am in favor of closing it.
