### ISSUE TITLE
Create new pattern for Template::Research-Help--Research-Help-Page

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#166]
## Testing

`dev` [/research/citing-and-using-sources](http://dev.libraries.emory.edu/research/citing-and-using-sources)
`qa` [/research/citing-and-using-sources](http://qa.libraries.emory.edu/research/citing-and-using-sources)

**Comment by kristianserrano** [comment]
@laurenhamel do you mind reviewing this?

**Comment by laurenhamel** [comment]
@kristianserrano, I'm moving this back to "In Progress" and changing the milestone to Sprint 10 because we won't be able to actually deploy it to `qa` until we export it into the templating engine and setup the mutations for it. Also, I'm currently unable to deploy to the Pattern Library, possibly due to connection issues today, but this should at least be ready to deploy there for acceptance of the pattern come Tuesday when back in the office. One comment that I did raise in the PR, though, was that the this pattern is lacking placeholders for the header and footer areas. This may be something to consider before acceptance.

@kristianserrano and @nikdragovic, I do have some concerns about the naming of things. While we originally were calling this page type "Library Aids," it looks like we're now leaning towards "Research Aids" or "Research Help," which is what this pattern was named (`templates-research-help`). I'm wondering if this will easily be confused with the Research Guides that exist for Subject Librarians.

**Comment by kristianserrano** [comment]
Well it looks it's going away altogether anyway, right?

**Comment by libdgg** [comment]
@kristianserrano just want to check that you aren't working on this. i believe it could be moved out of sprint 10 and worked on later. please let me know and i can move it.

**Comment by kristianserrano** [comment]
I am not planning to continue work on this at all unless it's determined that Research Help will again be a page type on the site.

**Comment by kristianserrano** [comment]
@libdgg and @laurenhamel it looks like according to feedback from Chris Palozzolo and Kim Collins that we'll still need to provide this template which is being used for the "Finding Films and Video" page.
See https://github.com/emory-libraries/web-redesign/issues/172#issuecomment-497458162

**Comment by libdgg** [comment]
@kristianserrano moving this to Sprint 15 for future review/work.

**Comment by laurenhamel** [comment]
Reassigning this issue to myself to redistribute points.

**Comment by laurenhamel** [comment]
I'm moving this issue into blocked for the time being. I think there will need to be some updates to the data definition in Cascade before we can fully move forward with updating the pattern and working toward integrating this template into the templating engine.

**Comment by nikdragovic** [comment]
@kristianserrano, are you getting notifications today?

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. It includes modifications to the `templates-info`, `templates-material`, and `templates-tool` pages as well to account for changes I made to `organisms-main`. These changes mainly include the addition of resources and contacts data (blue/white bar areas) per emory-libraries/web-redesign#170, and since I was already applying some updates to those template patterns, I also went ahead and added the sidebar content in the info page template. @nikdragovic, just a heads up to you also that these enhancements are pending.

**Comment by nikdragovic** [comment]
Thanks for carrying this forward @laurenhamel

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance and has been deployed to `qa`. Check the description above for testing links.

**Comment by nikdragovic** [comment]
Thanks, @laurenhamel. I added dummy Contact Links and Resource Links to see how those display, and they look great. I think the generic pattern should be more helpful to stakeholders since they can leverage the fields more flexibly.

**Comment by nikdragovic** [comment]
@kristianserrano @laurenhamel I am accepting this issue as complete. We are planning to make sure the new Ready/Done board columns are in place during retrospective Monday. In that column structure, I'd be moving this issue to "Deploy to Production." I'll move it to "To Accept for Launch" for now? Let me know if I need to close it instead for the purposes of velocity tracking.
