### ISSUE TITLE
Create new pattern Template::Exhibition--Exhibit

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#175]

**Comment by laurenhamel** [comment]
This is mostly done but is dependent on #188 and pending modifications to the Cascade data definition.

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing. It's worth noting, though, that some changes will need to be made to this once @nikdragovic confirms about the inclusion of Exhibition events. If we're relying on the Trumba feed's JSON, then we may want to update in a later sprint when we incorporate RSS feed parsing into the templating engine. Otherwise, if it makes more sense for content editors to manually enter event information, then we'll need to update the DD in Cascade as well as the template and its mutations to match, which could theoretically happen before the end of Sprint 11 if time permits.

**Comment by nikdragovic** [comment]
@laurenhamel, let's surface the question at standup tomorrow; I think it
would benefit from discussion so I can make sure I'm interpreting
it correctly.

**Comment by nikdragovic** [comment]
Reference links: 

https://cascade.emory.edu/entity/open.act?id=ea789bd70ae7209842afc98c6189dc99&type=page

http://qa.libraries.emory.edu/events-and-exhibits/exhibits/punks-not-dead
