### ISSUE TITLE
Create new pattern Template::Archive-Results

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#177]

**Comment by laurenhamel** [comment]
@kristianserrano, similar question here for you like I posted on #178. Are you thinking this invalid for the time being because our intended use of WordPress for news and blogs? For this page type specifically, I can definitely see us holding off on implementation until later down the road if/when we so choose to as an enhancement. I do wonder if the news archive directory page in #178 is still relevant, though.

**Comment by kristianserrano** [comment]
Yes, it's invalid for that reason. WordPress handles that feature for us.

**Comment by laurenhamel** [comment]
Closing because this was marked as invalid. A new issue can be opened in the future if circumstances related to this changes.
