### ISSUE TITLE
Create new pattern Organism::Search-Menu

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#204]
## Testing

`pattern-library` [organisms-search-menu](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=organisms-search-menu)

**Comment by laurenhamel** [comment]
@kristianserrano, in looking at this pattern, I think this is overlapping with what you're trying to do. Originally, I separated the tab menus and search menus, but based on our conversations earlier today, it sounds like you may be incorporating the two into one, which isn't a problem but may mean we need to reevaluate what this pattern looks like or if it's even needed still. My only concern with integrating the tabs and search menus is that we'll likely need variants for both the home page's intro section and the header navigation area.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm dropping some notes here for you in case you pick this issue up over the weekend. I may touch base with you Sunday to see where you're at with this and/or if you ran into any roadblocks.

I had previously merged the `dev` branches into the `template-sass` and `pattern-library` repos to include the deployed changes for the `compounds-tab-menu` pattern and other updates, so they should already be included. As far as the `pattern-library` repo is concerned, in order to closeout this issue, the handlebars template needs to be built out along with it's Vue component. The `template-sass` repo should contain all the styles, with `-light` and `-dark` themes built in as well as a `-home` page style variation.

I had previously made some changes to `atoms-tab` and `compounds-tab-menu` patterns to include event broadcasting as well as the `atoms-search` pattern to include the optional cancel button, which was previously missing, and started configuring the search box component to listen for events. You'll likely need to review all of those to truly get a handle of what's going on, especially in terms of how the events are being registered and passed along.

Things that we may also want to do here (but may be better suited in a separate issue) is also go back and incorporate the search menu into the main mobile navigation menu, but I will defer to your better judgement on whether on not that's something you think we should tackle now or later. Lastly, if you do decide to try to incorporate the search menu into the main navigation, you may need to go back to the `template-sass` repo and update the styles either in the search menu (or overrides in the navigation menu) in order to have the full menu flyout and coverage like in the Figma design.

**Comment by laurenhamel** [comment]
@kristianserrano, I'm picking this issue back up this morning in hopes to knock it out before our meeting this evening.

**Comment by laurenhamel** [comment]
I added a comment into one of the PRs I opened for this issue to indicate that this pattern is "as is." I'm reposting that same comment here below so that others can easily find it later on:

Just as a side note, this is the core pattern for the search menu's Vue component, but because I kept running into issues with pattern lab not regenerating patterns after a change was made, I'm submitted this as is and will open a new issue to make sure the `noscript` part of the pattern gets added/fixed and is working as expected.

**Comment by laurenhamel** [comment]
@nikdragovic, this is ready for acceptance. See the testing link above. One thing worth noting is that, if you're testing out the search box's functionality, it may not execute searches correctly due to the pattern lab UI being within an iframe.

**Comment by nikdragovic** [comment]
@laurenhamel What is "Back to Menu" supposed to do, take the user back to the main nav?

Another question similar to 205 - are the text options hard-coded, or editable somewhere in the CMS?

**Comment by kristianserrano** [comment]
@nikdragovic back to menu will flip the search back to the main nav bar.

Yes, the options will be configurable via the CMS.

**Comment by nikdragovic** [comment]
Thanks @kristianserrano. I think I will need to make some edits to the labels and the placeholder text. Can you let me know which issue is associated with that CMS work, or is it already done/available?

**Comment by kristianserrano** [comment]
#nikdragovic I believe the DD is already done. I'll verify if I made it available in the Main site in Cascade when I get in to the office. (It might be in a global folder.)

**Comment by laurenhamel** [comment]
@nikdragovic, also to clarify, the DD in Cascade that @kristianserrano mentioned will be incorporated into the templates once the headers are added to pages, but the content you see here in the pattern library while reviewing is static merely placeholder content for us to just help you preview the design.

**Comment by nikdragovic** [comment]
@laurenhamel Yes thanks, that makes sense. Given our timeline and the upcoming demo, I just want to make sure I plan for the work I need to do.

**Comment by nikdragovic** [comment]
@laurenhamel The Viget design had "Cancel," we have "Clear." Do you have any opinion on why this is needed or useful?

**Comment by kristianserrano** [comment]
@nikdragovic I made that call because that's actually what the link does. I felt that when coupled with the Back to Menu button, it wasn't clear and obvious what "Cancel" would do. Does it clear the fields or does it flip the search menu back to the Nav menu? (It actually clears it.)

**Comment by laurenhamel** [comment]
@nikdragovic, @kristianserrano felt that the "Clear" label would provide more clarity rather than simply "Cancel" because the cancel button/link could also imply that the menu should close despite the "Back to Menu" button also being present. Ideally, though, this would be a scenario where we'd want to test with users before making any final decision about the labeling of things.

**Comment by nikdragovic** [comment]
@laurenhamel @kristianserrano Accepting, we can turn this into a new issue for enhancement.
