### ISSUE TITLE
Create new pattern Compound::Alert

### ISSUE THREAD

**Issue by kristianserrano** [emory-libraries/Pattern-Library#212]
## Testing

`pattern-library` [compounds-alert](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=compounds-alert)

**Comment by laurenhamel** [comment]
@kristianserrano, this is ready for testing.  As a side note, I left this pattern out of the header (#201) when building it out because I decided that the sticky/fixed positioning of the header wouldn't play nicely with trying to group these alerts into it. Instead, I'm thinking we'll just want to add a block for alerts below the header and above body content across all page templates.

**Comment by laurenhamel** [comment]
This is ready for acceptance. See above for testing links. Do note, this is only visual and functional testing and acceptance at this time as this pattern has not yet been integrated into our template pages.
