### ISSUE TITLE
Consider updating ID attributes to classes

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#332]
An ID attribute must be unique per page. If one page has duplicate IDs referenced, this can lead to accessibility issues. The simplest solution is to remove these IDs,  unless they are attached to CSS styles or a JS event.
If attached to styles or events, it is recommended to use classes, which can be used multiple times, instead.

The  <svg>  logo seems to suffer from this issue. It contains both IDs...
* id=”logo”
* id=”badge”

...and these appear multiple times per page, seen below:

![Screen Shot 2019-12-03 at 5.01.21 PM.png](https://images.zenhubusercontent.com/5c35178086008d0a2e1830d9/2cf84a84-48aa-496c-85a3-2543cc71e8b2)

**Comment by kristianserrano** [comment]
@rosy1280 the ids have been completely removed from the logos. Currently, the CSS has selectors for both the id and the class for the badge background color in the footer. HH will need to change the SVG in the velocity to use classes instead of IDs.

[Example in the pattern library](http://template.library.emory.edu/styleguide/patternlibrary/current/patterns/00-meta-20-assets-logos/00-meta-20-assets-logos.html).
