### ISSUE TITLE
Switch the image we pull from Trumba

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#337]
Right now on events pages we pull the event image from the Trumba `json`.  This creates some awkward cropping of images. See the [framing shadows event page](https://staging.libraries.emory.edu/events-and-exhibits/event.html?id=131265604) as an example. 

Unfortunately the event image is also being used by the digital signs. The aspect ratio needed for the event type page is 125/54 and the digital sign's aspect ratio is 200/200.  Ideally we would pull the detail image from Trumba rather than the event image.

**Comment by rosy1280** [comment]
@kristianserrano when this gets deployed to the server can you assign this to me so i can test and start working on cropping all those images?

**Comment by kristianserrano** [comment]
@rosy1280 While I have fixed this in the Pattern Library, HH will need to make the change from `eventImage` to `detailImage` in the velocity format here:
https://cascade.emory.edu/entity/open.act?id=3d32a9820ae720985a83bda0df78f3c4&type=format

I made the change, republished the page, and reverted the change back in Cascade so that HH could maintain their continuity of changes. I'm more than happy to revert back to my version if they want to just use that.

**Comment by kristianserrano** [comment]
@rosy1280 Do you want to close this since it's taken care of in Cascade already?
