### ISSUE TITLE
Footer dropdown links not working

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#356]
the Select a Location dropdown isn't creating the appropriate links to sites contained within https://libraries.emory.edu; for example selecting Woodruff directs you to `https://woodruff/index.html` rather than `https://libraries.emory.edu/woodruff/index.html`

Update the vue.js in the pattern library to appropriately handle these links

**Comment by kristianserrano** [comment]
@rosy1280 I have this in master and will deploy to staging and the pattern library on the morning of the 7th for testing.

**Comment by kristianserrano** [comment]
@rosy1280 I've published a test of this using the homepage on [staging.libraries.emory.edu](https://staging.libraries.emory.edu). Note that only the homepage has this fix because it's the only one pointing to the JS in the staging folder, but you can test all of the links on that page if you'd like.
