### ISSUE TITLE
Calendar of Events page does not pull current month

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/Pattern-Library#358]
The calendar of events template doesn't pull events for the current month.  Acceptance criteria enumerated below:

- [x] The page should pull events from the feed for the current month; note this may mean the calendar of events template displays events that have already past, that is ok.
- [x] Ideally the page would list all future events.  If that isn't possible, then the page should pull events from the feed for at least the next month and the 2 following month; i.e. the 3 months following the current month.  
- [x] nothing else about the page should change

**Comment by kristianserrano** [comment]
This fix can be tested in the [calendar events page in staging](https://staging.libraries.emory.edu/events-exhibits/events/index.html).

The issue was with the use of the `_.compact()` method in Lodash which strips out all "falsey" values, including `0` which is January. The solution was to convert the values to strings so that the value of `0` would stay in the array as `"0"`.

**Comment by kristianserrano** [comment]
@rosy1280 this fix can be tested in the [calendar events page in staging](https://staging.libraries.emory.edu/events-exhibits/events/index.html).

The issue was with the use of the `_.compact()` method in Lodash which strips out all "falsey" values, including `0` which is January. The solution was to convert the values to strings so that the value of `0` would stay in the array as `"0"`.

**Comment by kristianserrano** [comment]
Reminder: Resolve [INC03301668](https://emory.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=ef4373a41bd20018522e964ead4bcb2f%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) after solution has been deployed to production.
